export const VIETNAM_CITIES = [
  { id: 1, name: 'Hà Nội', code: 'HAN' },
  { id: 2, name: 'Hồ Chí Minh', code: 'SGN' },
  { id: 3, name: 'Đà Nẵng', code: 'DAD' },
  { id: 4, name: 'Hải Phòng', code: 'HPH' },
  { id: 5, name: 'Cần Thơ', code: 'VCA' },
  { id: 6, name: 'Nha Trang', code: 'CXR' },
  { id: 7, name: 'Huế', code: 'HUI' },
  { id: 8, name: 'Đà Lạt', code: 'DLI' },
  { id: 9, name: 'Phú Quốc', code: 'PQC' },
  { id: 10, name: 'Vũng Tàu', code: 'VTG' },
  { id: 11, name: 'Quy Nhơn', code: 'UIH' },
  { id: 12, name: 'Vinh', code: 'VII' },
  { id: 13, name: 'Buôn Ma Thuột', code: 'BMV' },
  { id: 14, name: 'Pleiku', code: 'PXU' },
  { id: 15, name: 'Hạ Long', code: 'VDO' },
  { id: 16, name: 'Cà Mau', code: 'CAH' },
  { id: 17, name: 'Rạch Giá', code: 'VKG' },
  { id: 18, name: 'Thanh Hóa', code: 'THD' },
  { id: 19, name: 'Tuy Hòa', code: 'TBB' },
  { id: 20, name: 'Côn Đảo', code: 'VCS' },
  { id: 21, name: 'Điện Biên Phủ', code: 'DIN' },
  { id: 22, name: 'Hà Giang', code: 'VGI' },
  { id: 23, name: 'Sapa', code: 'SAP' },
  { id: 24, name: 'Phan Thiết', code: 'PHT' },
  { id: 25, name: 'Mũi Né', code: 'MNE' },
  { id: 26, name: 'Long Xuyên', code: 'LXU' },
  { id: 27, name: 'Châu Đốc', code: 'CHD' },
  { id: 28, name: 'Mỹ Tho', code: 'MTH' },
  { id: 29, name: 'Bến Tre', code: 'BTR' },
  { id: 30, name: 'Trà Vinh', code: 'TVN' },
  { id: 31, name: 'Sóc Trăng', code: 'STG' },
  { id: 32, name: 'Bạc Liêu', code: 'BLI' },
  { id: 33, name: 'Hà Tiên', code: 'HTI' },
  { id: 34, name: 'Tây Ninh', code: 'TYN' },
  { id: 35, name: 'Biên Hòa', code: 'BHO' },
  { id: 36, name: 'Thủ Dầu Một', code: 'TDM' },
  { id: 37, name: 'Long Khánh', code: 'LKH' },
  { id: 38, name: 'Vĩnh Long', code: 'VLO' },
  { id: 39, name: 'Sa Đéc', code: 'SDC' },
  { id: 40, name: 'Cao Lãnh', code: 'CLH' },
  { id: 41, name: 'Hội An', code: 'HOI' },
  { id: 42, name: 'Tam Kỳ', code: 'TAK' },
  { id: 43, name: 'Quảng Ngãi', code: 'QNG' },
  { id: 44, name: 'Kon Tum', code: 'KTU' },
  { id: 45, name: 'Đắk Lắk', code: 'DLK' },
  { id: 46, name: 'Gia Lai', code: 'GLA' },
  { id: 47, name: 'Lâm Đồng', code: 'LDG' },
  { id: 48, name: 'Ninh Thuận', code: 'NTH' },
  { id: 49, name: 'Bình Thuận', code: 'BTH' },
  { id: 50, name: 'Bình Dương', code: 'BDG' },
  { id: 51, name: 'Đồng Nai', code: 'DNI' },
  { id: 52, name: 'Bình Phước', code: 'BPC' },
  { id: 53, name: 'Nghệ An', code: 'NAN' },
  { id: 54, name: 'Hà Tĩnh', code: 'HTN' },
  { id: 55, name: 'Quảng Bình', code: 'QBH' },
  { id: 56, name: 'Quảng Trị', code: 'QTR' },
  { id: 57, name: 'Thừa Thiên Huế', code: 'TTH' },
  { id: 58, name: 'Quảng Nam', code: 'QNA' },
  { id: 59, name: 'Bắc Ninh', code: 'BNI' },
  { id: 60, name: 'Hải Dương', code: 'HDG' },
  { id: 61, name: 'Hưng Yên', code: 'HYE' },
  { id: 62, name: 'Nam Định', code: 'NDI' },
  { id: 63, name: 'Thái Bình', code: 'TBN' },
];

export const INTERNATIONAL_CITIES = [
  { id: 101, name: 'Bangkok', code: 'BKK', country: 'Thailand' },
  { id: 102, name: 'Singapore', code: 'SIN', country: 'Singapore' },
  { id: 103, name: 'Kuala Lumpur', code: 'KUL', country: 'Malaysia' },
  { id: 104, name: 'Seoul', code: 'ICN', country: 'South Korea' },
  { id: 105, name: 'Tokyo', code: 'NRT', country: 'Japan' },
  { id: 106, name: 'Hong Kong', code: 'HKG', country: 'Hong Kong' },
  { id: 107, name: 'Taipei', code: 'TPE', country: 'Taiwan' },
  { id: 108, name: 'Manila', code: 'MNL', country: 'Philippines' },
  { id: 109, name: 'Jakarta', code: 'CGK', country: 'Indonesia' },
  { id: 110, name: 'Bali', code: 'DPS', country: 'Indonesia' },
  { id: 111, name: 'Dubai', code: 'DXB', country: 'UAE' },
  { id: 112, name: 'Sydney', code: 'SYD', country: 'Australia' },
  { id: 113, name: 'Melbourne', code: 'MEL', country: 'Australia' },
  { id: 114, name: 'Paris', code: 'CDG', country: 'France' },
  { id: 115, name: 'London', code: 'LHR', country: 'UK' },
  { id: 116, name: 'Los Angeles', code: 'LAX', country: 'USA' },
  { id: 117, name: 'San Francisco', code: 'SFO', country: 'USA' },
  { id: 118, name: 'New York', code: 'JFK', country: 'USA' },
];
